export const QuoteArray = [
   " “War never changes.” – Sole Survivor",
   " “Ideals are strengthened by the challenges they endure.” – Courier Six",
    "“You’re a single bomb in an arsenal of thousands, preparing to lay waste to what’s left of mankind!” – Arthur Maxson",
    "“I don’t enjoy killing, but when done righteously, it’s just another chore.” – Joshua Graham" ,
    "“Who do you think actually won the war? No one, I guess.” – Nick Valentine ",
    "“If you want to see the fate of democracies, look out the windows.” – Robert House ",
    "“Waging war against good people is bad for the soul.” – Joshua Graham",
    "“It was just me against the world, and the world had it coming.” – Conrad Kellogg ",
    "“Hey, chin up. I know the night just got darker, but it won’t last forever.” – Nick Valentine ",
    "“There really is no way to ride a seesaw with dignity.” – Nick Valentine",
    "“If you believe in something enough, you must be willing to let it burn, lest it claim you.” – Ulysses",
    "16. “If you find any pieces of my legs, could you pick them up for me?” – Nick Valentine",
    "“Don’t get me started on the futility of dusting a collapsed house!” – Codsworth",
    "“My name is Mister Handy, tidier of things. Look upon this room I said I’d cleaned, and despair.” – Nick Valentine ",
    "“You will not be loved, but you will save humanity.” – Mama Murphy",
    "“In a hundred years, when I finally die, I only hope I go to Hell, so I can kill you all over again, you piece of shit.” – Sole Survivor ",
    "“To the world that was. Mankind shall never see it like again.” – Richard Bradford",
    "“Protect the people at a minute’s notice.” – Preston Garvey",
    "“Fight Apathy! Or don’t.” – Graffiti",
    "“Death is a preferable alternative to communism.” – Liberty Prime",
    "“Truth is, the game was rigged from the start.” – Benny",
    "“Rangers are volunteers. Every man and woman who signs up is willing to die for the NCR. Myself included.” – Chief Hanlon",
    "“It’s said war—war never changes. Men do, through the roads they walk. And this road—has reached its end.” – Ulysses",
    "“Look around you, Danse. Look at the scorched earth and the bones that litter the Wasteland. Millions, perhaps even billions, died because science outpaced man’s restraint! They called it a ‘new frontier’ and ‘pushing the envelope,’ completely disregarding the repercussions! Can’t you see that the same thing is happening again?!” – Arthur Maxson",
    "“Followed by—yes, followed by flashes. Blinding flashes, sounds of explosions, we’re—we’re trying to get confirmation, but we seem to have lost contact with our affiliate stations. We do have coming in confirmed reports—I repeat, confirmed reports of nuclear detonations in New York and Pennsylvania. My God.” – Newscaster",
    "“I am the bringer of death. Fall to your knees and beg for mercy, or give me a sandwich. I’m pretty hungry.” – Vault Dweller",
    "“Baby, getting outplayed and getting cheated ain’t the same thing.” – Benny",
    "“Haven’t you been paying attention? You don’t find the Institute. The Institute finds you. You open the closet. It’s just a closet. You can never find the monster that hides inside. Not until it jumps out at you.” – Conrad Kellogg",
    "“It’s a thing, a science thing. It hurts robots. Don’t worry about it.” – Arcade Gannon",
    "“The women of New Vegas ask me a lot if there’s a Mrs. New Vegas. Well, of course, there is. You’re her, and you’re still as perfect as the day we met.” – Mr. New Vegas",
    "“You’re damn straight. This is my place! Now, get the hell out before I make your head a wall decoration!” – Mayor Killian Darkwater",
    "“We’re citizen soldiers. The people of the Commonwealth banding together to protect ourselves and decide our own future. That was the original idea, and it was a good one.” – Preston Garvey",
    "“It’s a game, and games have winners and losers. I prefer the former, how about you?” – Benny",
    "“By my calculations, the easiest way to help a human is simply to destroy it. There’s no point in prolonging a laughably fragile life.” – Jezebel",
    "“It’s obvious that kindness and good temper aren’t part of this religion.” – Vault Dweller",
    "“The Brotherhood is a collective of men and women who have dedicated their lives to the preservation of technology.” – Darrel",
    "“I’ve got a weapon for every situation. Hunting, protection, cold-blooded murder, hot-blooded murder—.” – KL-E-0",
    "“I will conquer it and turn all those pure strain humans into mutants. They will give me the army I need to bring peace to the entire wasteland.” – Master",
    "“Look, buddy, my job here is to keep the peace, and if I have to break a few heads to do it, then a few people are going to be hurting. So, just watch it.” – Lars",
    "“People enjoyed luxuries, once thought the realm of science fiction—domestic robots, fusion-powered cars, portable computers. But then, in the 21st century, people awoke from the American Dream. Years of consumption led to shortages of nearly every major resource. The entire world unraveled. Peace became a distant memory. It is now the year 2077. We stand on the brink of total war, and I am afraid.” – Sole Survivor",
    "“Spare change, old friend, old pal? Can you help a poor mutant down on his luck?” – Harold",
    "War. War never changes.",
    "You will be faced with many challenges throughout your lifetime, and the most difficult of these will be dealing with your fellow man. There will come a time when diplomacy and tact will prove to be useless and your hand must be raised instead. — Cameron",
    "What do I want? I don't really know. Most of the time I ignore my quest and walk into the homes of others, riffling through people's shelves... oooh, like those over there! - The Chosen One" ,
    "Parents? Hah! I was born from the sun and have sand in my veins! --Three Dog",
    "\"This next piece reminds me of something my husband said: Friendship is like a violin. Even if the music stops, you'll still have the strings.\"— Agatha",
    "\"Humanity is so resilient, to cling to life despite all of this. It is the duty of us all to further that survival.\"—Curie",
    "\"Now, before you set off on your grand Nuka-Adventure, let me tell you about error system malfunction\" —N.I.R.A.",
    "\"Damn you, Weatherby Savings and Loan! I spit at thee!\"—Captain Ironsides"
]
    
    export default [QuoteArray]