export const ClothingArray = [
[    `1st Recon Beret`,12 ],
[`Airship Captain's Hat`,5],
[`Assault Gas Mask`,2],
[`Atom Cats Jacket And Jeans`, 12],
[`Aviator Cap`,16],
[`Baseball Cap`,5],
[`Battered Fedora`,12],
[`Bowler Hat`,7],
[`Brotherhood of Steel Hood`,7],
[`Camouflage`,22],
[`Dirty Postman Uniform`, 12],
[`Dog Bandanna`,7],
[`Enclave Officer's Hat`, 5],
[`Eyeglasses`,7],
[`Institute Division Head Coat`,7 ],
[`Institute Lab Coat`,7 ],
[`Leg Guards`, 8],
[`Limb Braces`, 12],
[`Magnifying Visor`, 8],
[`Military Fatigues`, 7],
[`NCR Jumpsuit`,15],
[`Patched Three - Piece Suit`, 12],
[`Red Flight Helmet`, 5],
[`Road Goggles`,7],
[`Robotic Bits`,7],
[`Sea Captain's Hat`,7],
[`Shoulder Rags`,10],
[`Spiked Muzzle`,3],
[`Tricorn Hat`,7],
[`Triggerman Bowler`,5],
[`Vault 111 Jumpsuit`,12]
]

export default ClothingArray