export const FoodArray = [
    ["Bloatfly Meat", 17],
["Blood Pack", 15],
["Brahmin Meat", 20],
["Caravan Lunch", 16],
["Cave Fungus", 8],
["Cram", 12],
["Deathclaw Meat", 29],
["Fog Crawler Meat", 23],
["Fresh Melon", 9],
["Gecko Kebab", 20],
["Honey Mesquite Pod", 5],
["Iguana Bits", 20],
["Iguana On A Stick", 15],
["Mirelurk Meat", 20],
["Mole Rat Meat", 24],
["Mutant Hound Meat", 22],
["Nuka-Cherry", 20],
["Nuka-Cola", 15],
["Nuka-Cola Quantum", 41],
["Queen Mirelurk Meat", 12],
["Radroach Meat", 9],
["Radscorpion Egg", 23],
["Radscorpion Meat", 24],
["Radstag Meat", 24],
["Squirrel Bits", 9],
["Squirrel on a Stick", 15],
["Squirrel Stew", 20],
["Sugar Bombs", 9],
["Tato and Water", 9],
["Yao Guai Meat", 29],
["Yao Guai Rib Meat", 24]
]

export default FoodArray