export const GearArray= [
    [`Admin Password`, 25],
[`Artillery Smoke Grenade`, 4],
[`Armor Piercing Ammo`, 1],
[`Binoculars`, 4],
[`Car Security Override`, 1],
[`Chemical Coating`, 10],
[`Climbing Spikes`, 2],
[`Creature Patch`, 15],
[`Custom Ammo`, 15],
[`Dead Man's Switch`, 8],
[`Deathclaw Control Scrambler`, 10],
[`Domestication Unit`, 12],
[`Draft Codex`, 9],
[`Fire Extinguisher`, 4],
[`Flashlight`, 3],
[`Fragile Bobby Pin`, 4],
[`Fusion Core`, 10],
[`Gen 1 Synth Override`, 15],
[`Hand-Written Note`, 25],
[`Mirelurk Eggs`, 12],
[`Mr Handy Fuel`, 4],
[`Overclocker`, 14],
[`Pheromone Emitter`, 8],
[`Pheromone Mask`, 12],
[`Power Armor Patch`, 5],
[`Pulse Shield`, 13],
[`Robobrain Arms`, 5],
[`Robot Repair Kit`, 18],
[`Robot Repair Patch`, 10],
[`Rope`,2],
[`Snakebite Tourniquet`, 2],
[`Skeleton Key`, 25],
[`Synthbooster`, 20],
[`Stealth Boy`, 22],
[`Stethoscope`, 4],
[`Stuffed Monkey`, 5],
[`Temporary Password`, 4],
[`Third-Arm Clamp`, 4],
[`Turret Inhibitors`, 3],
[`Unsent Letter`, 50],
[`Vertibird Signal Grenade`, 4],
[`Zapper`, 8]
]

export default GearArray