export const MeleeArray = [
['Ballistic Fist', 16],
[`Baseball Bat`, 1],
[`Baton`, 10],
[`Board`, 8],
[`Cattle Prod`, 3],
[`Chinese Officer's Sword`, 7],
[`Deathclaw Gauntlet`, 15],
[`Dog Tag Fist`, 2],
[`Fire Axe`, 10],
[`Fire Hydrant Bat`, 38],
[`Hand Saw Blade`, 6],
[`Hand Shock`, 25],
[`Hand Vice Grip`, 3],
[`Huge Club`, 21],
[`Lead Pipe`, 9],
[`Machete`, 1],
[`Machete Gladius`, 3],
[`Nail Board`, 1],
[`Pipe Wrench`, 6],
[`Power Fist `, 3],
[`Rebar Club`, 18],
[`Ripper`, 6],
[`Shishkebab`, 15],
[`Sledgehammer`, 12],
[`Spear`, 4],
[`Stun Baton`, 25],
[`Super Sledge`, 30],
[`Thermic Lance `, 35],
[`Tire Iron`, 12],
[`Vertibird Blade`, 22]
] 

export default MeleeArray