export const PistolArray = [
    ['.357 Magnum Revolver', 8],
['.44 Magnum Revolver', 8],
['.44 Revolver', 6],
['10mm Pistol', 6],
['12.7mm Pistol', 4],
['Alien Blaster', 9],
['Bolt-Action Pipe Pistol', 1],
['Eyebot Laser', 4],
['Eyebot Tesla Cannon', 12],
['Flare Gun', 5],
['Gamma Gun', 13],
['Hand Cryojet', 10],
['Hand Gamma Gun', 15],
['Hand Lightning Gun', 4],
['Hand Nail Gun', 7],
['Hunting Revolver', 7],
['Institute Laser Pistol', 3],
['Laser Pistol', 7],
['Mr Handy Flamer', 10],
['Pipe Pistol', 2],
['Plasma Defender', 12],
['Plasma Pistol', 6],
['Protectron Hand Laser', 10],
['Pulse Gun', 11],
['Ranger Sequoia', 13],
['Robobrain Mesmetron', 15],
['Thirst Zapper Cola', 2]
]

export default PistolArray