export const RifleArray = [
    [`Anti-Material Rifle`, 37],
    [`Assault Carbine`, 10],
    [`Assault Rifle`, 8],
    [`Assaultron Head Laser`, 40],
    [`Battered Assaultron Head Laser`, 30],
    [`Bolt-Action Pipe Rifle`, 10],
    [`Caravan Shotgun`, 12],
    [`Combat Rifle`, 16],
    [`Combat Shotgun`, 10],
    [`Cowboy Repeater`, 11],
    [`Double-Barrel Shotgun`, 12],
    [`Flamer`, 24],
   [`Gauss Rifle`, 42],
    [`Grenade Launcher`, 35],
    [`Hunting Rifle`, 20],
    [`Hunting Shotgun`, 9],
    [`Institute Laser Rifle`, 10],
    [`Laser Musket`, 14],
    [`Laser Rifle`, 30],
    [`Laser Turret`, 10],
    [`Marksman Carbine`, 14],
    [`Pipe Rifle`, 8],
    [`Plasma Rifle`, 24],
    [`Railway Rifle`, 20],
    [`Sawed-Off Shotgun`, 15],
    [`Service Rifle`, 10],
    [`Sniper Rifle`, 26],
    [`Submachine Gun`, 10],
    [`Tesla Rifle`, 20],
    [`Trail Carbine`, 26],
]

export default RifleArray